### ISSUE TITLE
Traceback

### ISSUE THREAD

**Issue by jfrantz2** [Darkman802/Super-Hexagon-Bot#1]
![capture](https://cloud.githubusercontent.com/assets/684272/6258811/d04f47ac-b799-11e4-94aa-d8784282f0f0.PNG)

Please look at the image; having a problem running the script.

Python: 2.7.5 (32-bit)
Pywin32: 2.7 version (32-bit)

**Comment by ghost** [comment]
You need to use python 3, from_bytes is new in version 3.2

**Comment by jfrantz2** [comment]
Confirmed working with >=3.2
